### ISSUE TITLE
Не стартует видеопоток

### ISSUE THREAD

**Issue by pro777s** [sshmanko/acestream-armv7#14]
При попытке запустить: 
wget http://localhost:6878/ace/getstream?infohash=--infohash--
В логе выдается:
"2019-11-11 17:48:10,110|Thread-84|acestream.RequestBroker|process_dash_request:manifest: error
Traceback (most recent call last):
  File "core.c", line 768, in
  File "core.c", line 164, in
AttributeError: 'Android' object has no attribute 'startInternalActivity'"
Версия: {"result": {"code": 3013300, "platform": "android", "version": "3.1.33"}, "error": null}
В чем может быть дело?

**Comment by Nikfr** [comment]
Аналогично, прокси работает, а VLC выдает
 access stream error: HTTP 500 error
 http stream error: error: HTTP/1.0 500 Internal Server Error
main input error: Your input can't be opened
main input error: VLC is unable to open the MRL 'http://127.0.0.1:6878/ace/getstream?id=hash'. Check the log for details.
